import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Home from './page'



const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Rock, Paper, Scissors, Lizard, Spock',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-radial h-screen w-screen bg-top bg-cover from-[#1F3756] to-[#141539]'>
        <Home />
        <footer className='flex justify-center items-center'>
          <span className='text-white text-sm'>Frontend Mentor Challenge | Code by Junior</span>
        </footer>
      </body>

    </html>
  )
}
